# Generated by Django 2.2.5 on 2019-09-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='applicants',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
